# FIXME: префикс добавляется ко всему в т.ч. к фронту
# найти грамотное решение и убрать из контроллеров префикс /api
# server:
#   servlet:
#     context-path: /api

spring:
  application:
    name: taskManager

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true
