---

# spring.jpa.hibernate.ddl-auto=none
spring:
  datasource:
    url: jdbc:h2:mem:javaspringblog_development
    driverClassName: org.h2.Driver
    username: tirion
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # logging:
  #   level:
  #     org.springframework.web: DEBUG
  #     guru.springframework.controllers: DEBUG
  #     org.hibernate: DEBUG

# server:
#   tomcat:
#     accesslog:
#       enabled: true
#       buffered: false
