---

spring:
  datasource:
    url: jdbc:h2:file:./development
    driverClassName: org.h2.Driver
    user: tirion
    password: password

  jpa:
    open-in-view: false
    # hibernate:
    #   ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # liquibase:
  #   # change-log: classpath:db/changelog/changelog-master.yaml
  #   url: jdbc:h2:file:./development
  #   user: tirion
  #   password: password
  #   # drop-first: true
  #   # enabled: false

  logging:
    level:
      liquibase: info
  #     org.springframework.web: DEBUG
  #     guru.springframework.controllers: DEBUG
  #     org.hibernate: DEBUG

# server:
#   tomcat:
#     accesslog:
#       enabled: true
#       buffered: false
