---

spring:
  datasource:
    url: jdbc:h2:file:./development
    driver-class-name: org.h2.Driver
    user: tirion
    password: password

  jpa:
    # open-in-view: false
    # hibernate:
    #   ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  # liquibase:
  #   # change-log: classpath:db/changelog/changelog-master.yaml
  #   url: jdbc:h2:file:./development
  #   user: tirion
  #   password: password
  #   # drop-first: true
  #   # enabled: false

logging:
  level:
    root: debug
    org:
      springframework:
        test:
          context:
            cache: debug
      hibernate:
        type:
          descriptor:
            sql: trace
        SQL: debug
    #     type: debug
  #     org.springframework.web: DEBUG
  #     guru.springframework.controllers: DEBUG
  #     org.hibernate: DEBUG

# server:
#   tomcat:
#     accesslog:
#       enabled: true
#       buffered: false
