---

spring:
  datasource:
    url: jdbc:h2:file:./development
    driverClassName: org.h2.Driver
    username: tirion
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    # database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    # change-log: classpath:db/db.changelog-master.yml
    # drop-first: true
    # enabled: false

  # logging:
  #   level:
  #     org.springframework.web: DEBUG
  #     guru.springframework.controllers: DEBUG
  #     org.hibernate: DEBUG

# server:
#   tomcat:
#     accesslog:
#       enabled: true
#       buffered: false
