name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
      - run: make build
      - run: make test

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event_name == 'push' }}
  #
  #   steps:
  #     - uses: actions/checkout@v2
  #
  #     - uses: docker/setup-buildx-action@v1
  #
  #     - uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #
  #     - uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         push: true
  #         cache-from: hexletcomponents/java-spring-blog:latest
  #         cache-to: type=inline
  #         tags: hexletcomponents/java-spring-blog:latest
